// <auto-generated />
using System;
using EuroLeaguePlayerBuilder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuroLeaguePlayerBuilder.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131124147_InitialDatabaseCreated")]
    partial class InitialDatabaseCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EuroLeaguePlayerBuilder.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TitlesWon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Dimitris",
                            LastName = "Itoudis",
                            TitlesWon = 5
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Georgios",
                            LastName = "Bartzokas",
                            TitlesWon = 3
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Pablo",
                            LastName = "Laso",
                            TitlesWon = 4
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sarunas",
                            LastName = "Jasikevicius",
                            TitlesWon = 2
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Dejan",
                            LastName = "Radonjic",
                            TitlesWon = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Zvezdan",
                            LastName = "Mitrovic",
                            TitlesWon = 1
                        });
                });

            modelBuilder.Entity("EuroLeaguePlayerBuilder.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AssistsPerGame")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("PointsPerGame")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("ReboundsPerGame")
                        .HasColumnType("float");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssistsPerGame = 2.1000000000000001,
                            FirstName = "Ioannis",
                            LastName = "Papapetrou",
                            PointsPerGame = 12.5,
                            Position = "Small Forward",
                            ReboundsPerGame = 4.2999999999999998,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssistsPerGame = 7.4000000000000004,
                            FirstName = "Nick",
                            LastName = "Calathes",
                            PointsPerGame = 11.199999999999999,
                            Position = "Point Guard",
                            ReboundsPerGame = 3.5,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssistsPerGame = 1.3,
                            FirstName = "Dimitris",
                            LastName = "Mitoglou",
                            PointsPerGame = 10.1,
                            Position = "Power Forward",
                            ReboundsPerGame = 5.2000000000000002,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssistsPerGame = 1.2,
                            FirstName = "DeShaun",
                            LastName = "Thomas",
                            PointsPerGame = 9.3000000000000007,
                            Position = "Small Forward",
                            ReboundsPerGame = 4.0,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            AssistsPerGame = 0.90000000000000002,
                            FirstName = "Zach",
                            LastName = "LeDay",
                            PointsPerGame = 8.6999999999999993,
                            Position = "Center",
                            ReboundsPerGame = 5.5,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssistsPerGame = 0.5,
                            FirstName = "Moustapha",
                            LastName = "Fall",
                            PointsPerGame = 5.2000000000000002,
                            Position = "Center",
                            ReboundsPerGame = 4.7000000000000002,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssistsPerGame = 2.1000000000000001,
                            FirstName = "Sasha",
                            LastName = "Vezenkov",
                            PointsPerGame = 15.300000000000001,
                            Position = "Power Forward",
                            ReboundsPerGame = 5.7999999999999998,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            AssistsPerGame = 1.5,
                            FirstName = "Kostas",
                            LastName = "Papanikolaou",
                            PointsPerGame = 10.199999999999999,
                            Position = "Small Forward",
                            ReboundsPerGame = 4.0999999999999996,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            AssistsPerGame = 2.2999999999999998,
                            FirstName = "Giannoulis",
                            LastName = "Larentzakis",
                            PointsPerGame = 11.0,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 3.0,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            AssistsPerGame = 1.0,
                            FirstName = "Georgios",
                            LastName = "Printezis",
                            PointsPerGame = 9.5,
                            Position = "Power Forward",
                            ReboundsPerGame = 4.7999999999999998,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            AssistsPerGame = 1.1000000000000001,
                            FirstName = "Shaquielle",
                            LastName = "McKissic",
                            PointsPerGame = 8.1999999999999993,
                            Position = "Small Forward",
                            ReboundsPerGame = 3.2000000000000002,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 12,
                            AssistsPerGame = 0.80000000000000004,
                            FirstName = "Othello",
                            LastName = "Hunter",
                            PointsPerGame = 7.5,
                            Position = "Center",
                            ReboundsPerGame = 5.0,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            AssistsPerGame = 5.5,
                            FirstName = "Sergio",
                            LastName = "Llull",
                            PointsPerGame = 12.300000000000001,
                            Position = "Point Guard",
                            ReboundsPerGame = 2.3999999999999999,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 14,
                            AssistsPerGame = 0.69999999999999996,
                            FirstName = "Walter",
                            LastName = "Tavares",
                            PointsPerGame = 9.0,
                            Position = "Center",
                            ReboundsPerGame = 6.7999999999999998,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 15,
                            AssistsPerGame = 1.2,
                            FirstName = "Anthony",
                            LastName = "Rudy",
                            PointsPerGame = 10.5,
                            Position = "Small Forward",
                            ReboundsPerGame = 4.2999999999999998,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 16,
                            AssistsPerGame = 2.0,
                            FirstName = "Edgar",
                            LastName = "Sosa",
                            PointsPerGame = 8.6999999999999993,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.1000000000000001,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 17,
                            AssistsPerGame = 1.0,
                            FirstName = "Guerschon",
                            LastName = "Yabusele",
                            PointsPerGame = 9.1999999999999993,
                            Position = "Power Forward",
                            ReboundsPerGame = 3.7999999999999998,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 18,
                            AssistsPerGame = 2.1000000000000001,
                            FirstName = "Fabien",
                            LastName = "Causeur",
                            PointsPerGame = 11.0,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.5,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 19,
                            AssistsPerGame = 1.6000000000000001,
                            FirstName = "Nikola",
                            LastName = "Mirotic",
                            PointsPerGame = 13.1,
                            Position = "Power Forward",
                            ReboundsPerGame = 5.4000000000000004,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 20,
                            AssistsPerGame = 6.7999999999999998,
                            FirstName = "Nick",
                            LastName = "Calathes",
                            PointsPerGame = 11.0,
                            Position = "Point Guard",
                            ReboundsPerGame = 3.2000000000000002,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 21,
                            AssistsPerGame = 1.1000000000000001,
                            FirstName = "Brandon",
                            LastName = "Davies",
                            PointsPerGame = 10.199999999999999,
                            Position = "Center",
                            ReboundsPerGame = 5.7000000000000002,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 22,
                            AssistsPerGame = 2.2999999999999998,
                            FirstName = "Leandro",
                            LastName = "Bolmaro",
                            PointsPerGame = 9.5,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.7999999999999998,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 23,
                            AssistsPerGame = 1.5,
                            FirstName = "Jaka",
                            LastName = "Blazic",
                            PointsPerGame = 8.9000000000000004,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.0,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 24,
                            AssistsPerGame = 0.69999999999999996,
                            FirstName = "Pierre",
                            LastName = "Oriola",
                            PointsPerGame = 7.7999999999999998,
                            Position = "Power Forward",
                            ReboundsPerGame = 4.0,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 25,
                            AssistsPerGame = 1.8999999999999999,
                            FirstName = "Ognjen",
                            LastName = "Dobric",
                            PointsPerGame = 10.0,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.5,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 26,
                            AssistsPerGame = 0.80000000000000004,
                            FirstName = "Filip",
                            LastName = "Perrin",
                            PointsPerGame = 8.3000000000000007,
                            Position = "Center",
                            ReboundsPerGame = 4.5999999999999996,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 27,
                            AssistsPerGame = 1.2,
                            FirstName = "Branko",
                            LastName = "Lazić",
                            PointsPerGame = 7.9000000000000004,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.0,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 28,
                            AssistsPerGame = 1.3,
                            FirstName = "Jordan",
                            LastName = "Lyles",
                            PointsPerGame = 9.0999999999999996,
                            Position = "Small Forward",
                            ReboundsPerGame = 3.1000000000000001,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 29,
                            AssistsPerGame = 4.0,
                            FirstName = "Corey",
                            LastName = "Walden",
                            PointsPerGame = 11.199999999999999,
                            Position = "Point Guard",
                            ReboundsPerGame = 2.5,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 30,
                            AssistsPerGame = 1.0,
                            FirstName = "Marko",
                            LastName = "Simonovic",
                            PointsPerGame = 10.4,
                            Position = "Power Forward",
                            ReboundsPerGame = 5.2999999999999998,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 31,
                            AssistsPerGame = 2.5,
                            FirstName = "Kevin",
                            LastName = "Punter",
                            PointsPerGame = 12.199999999999999,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 3.1000000000000001,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 32,
                            AssistsPerGame = 0.90000000000000002,
                            FirstName = "Mathias",
                            LastName = "Lessort",
                            PointsPerGame = 9.5,
                            Position = "Center",
                            ReboundsPerGame = 5.2999999999999998,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 33,
                            AssistsPerGame = 1.2,
                            FirstName = "Nikola",
                            LastName = "Jovic",
                            PointsPerGame = 10.0,
                            Position = "Small Forward",
                            ReboundsPerGame = 3.7000000000000002,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 34,
                            AssistsPerGame = 0.80000000000000004,
                            FirstName = "Zlatko",
                            LastName = "Racic",
                            PointsPerGame = 8.5,
                            Position = "Power Forward",
                            ReboundsPerGame = 4.2000000000000002,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 35,
                            AssistsPerGame = 1.5,
                            FirstName = "Ognjen",
                            LastName = "Jaramaz",
                            PointsPerGame = 9.0,
                            Position = "Shooting Guard",
                            ReboundsPerGame = 2.7999999999999998,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 36,
                            AssistsPerGame = 3.8999999999999999,
                            FirstName = "Shawn",
                            LastName = "Hines",
                            PointsPerGame = 11.1,
                            Position = "Point Guard",
                            ReboundsPerGame = 2.5,
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("EuroLeaguePlayerBuilder.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Athens",
                            CoachId = 1,
                            Country = "Greece",
                            Name = "Panathinaikos"
                        },
                        new
                        {
                            Id = 2,
                            City = "Piraeus",
                            CoachId = 2,
                            Country = "Greece",
                            Name = "Olympiacos"
                        },
                        new
                        {
                            Id = 3,
                            City = "Madrid",
                            CoachId = 3,
                            Country = "Spain",
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 4,
                            City = "Barcelona",
                            CoachId = 4,
                            Country = "Spain",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 5,
                            City = "Belgrade",
                            CoachId = 5,
                            Country = "Serbia",
                            Name = "Crvena Zvezda"
                        },
                        new
                        {
                            Id = 6,
                            City = "Belgrade",
                            CoachId = 6,
                            Country = "Serbia",
                            Name = "Partizan"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EuroLeaguePlayerBuilder.Models.Player", b =>
                {
                    b.HasOne("EuroLeaguePlayerBuilder.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EuroLeaguePlayerBuilder.Models.Team", b =>
                {
                    b.HasOne("EuroLeaguePlayerBuilder.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuroLeaguePlayerBuilder.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
